"""Initial, revised from Int to Uuid

Revision ID: 33e738e4abe6
Revises:
Create Date: 2026-06-07 17:42:38.740913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33e738e4abe6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("macro_index_values")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_sessions_session_key"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_recommendations_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_asset_groups_id"), table_name="asset_groups")
    op.drop_table("asset_groups")
    op.drop_index(op.f("ix_portfolio_snapshots_id"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("macro_indices")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_indices",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("macro_indices_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("macro_indices_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "symbol",
            name=op.f("macro_indices_symbol_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("asset_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "value",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["asset_group_id"],
            ["asset_groups.id"],
            name=op.f("assets_asset_group_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("assets_pkey")),
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("recorded_at", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "total_value",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "base_currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_snapshots_pkey")),
        sa.UniqueConstraint(
            "recorded_at",
            name=op.f("portfolio_snapshots_recorded_at_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_id"), "portfolio_snapshots", ["id"], unique=False
    )
    op.create_table(
        "asset_groups",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("snapshot_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("country", sa.VARCHAR(length=2), autoincrement=False, nullable=False),
        sa.Column(
            "broker", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "total_value",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["portfolio_snapshots.id"],
            name=op.f("asset_groups_snapshot_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("asset_groups_pkey")),
    )
    op.create_index(op.f("ix_asset_groups_id"), "asset_groups", ["id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "portfolio_snapshot_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "action",
            postgresql.ENUM("BUY", "REDUCE", "HOLD", name="actiontype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sector", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "target_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column("recommended_month", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "confidence_score",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source_documents", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_snapshot_id"],
            ["portfolio_snapshots.id"],
            name=op.f("recommendations_portfolio_snapshot_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recommendations_pkey")),
    )
    op.create_index(
        op.f("ix_recommendations_id"), "recommendations", ["id"], unique=False
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "session_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "portfolio_snapshot_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_snapshot_id"],
            ["portfolio_snapshots.id"],
            name=op.f("chat_sessions_portfolio_snapshot_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_sessions_pkey")),
    )
    op.create_index(
        op.f("ix_chat_sessions_session_key"),
        "chat_sessions",
        ["session_key"],
        unique=True,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ASSISTANT", name="messagerole"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("chat_messages_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_messages_pkey")),
    )
    op.create_table(
        "macro_index_values",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("index_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("recorded_at", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.NUMERIC(precision=18, scale=4),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["index_id"],
            ["macro_indices.id"],
            name=op.f("macro_index_values_index_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("macro_index_values_pkey")),
        sa.UniqueConstraint(
            "index_id",
            "recorded_at",
            name=op.f("macro_index_values_index_id_recorded_at_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
